# This file was generated automatically by conda-forge (vn 0.1.0).




language: objective-c



env:


  matrix:
    
    - CONDA_NPY=18  CONDA_PY=27  
    
    - CONDA_NPY=18  CONDA_PY=34  
    
    - CONDA_NPY=18  CONDA_PY=35  
    
    - CONDA_NPY=19  CONDA_PY=27  
    
    - CONDA_NPY=19  CONDA_PY=34  
    
    - CONDA_NPY=19  CONDA_PY=35  
    






install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-3.7.3-MacOSX-x86_64.sh"
      wget "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client

      
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
